# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16FH822Nx3GITyWLF4xtJ11i3cJ71lcRl
"""

import math
import numpy as np
import matplotlib.pyplot as plt

# ---------------------- CONSTANTS ----------------------------

G = 9.80665                 # Gravity (m/s²)
R = 287.05                  # Specific gas constant for air (J/kg/K)
T0 = 288.15                 # Sea-level temperature (K)
P0 = 101325                 # Sea-level pressure (Pa)
LAPSE_RATE = 0.0065        # Temperature lapse rate (K/m)

# ---------------- ATMOSPHERIC MODEL --------------------------

def atmospheric_properties(altitude):
    """
    Calculates temperature, pressure and air density
    using the International Standard Atmosphere model
    for altitudes below 11 km.
    """
    if altitude < 0:
        altitude = 0

    if altitude <= 11000:
        temperature = T0 - LAPSE_RATE * altitude
        pressure = P0 * (temperature / T0) ** (G / (R * LAPSE_RATE))
        density = pressure / (R * temperature)
    else:
        # Simplified model above 11 km
        temperature_11 = T0 - LAPSE_RATE * 11000
        pressure_11 = P0 * (temperature_11 / T0) ** (G / (R * LAPSE_RATE))
        density_11 = pressure_11 / (R * temperature_11)
        scale_height = R * temperature_11 / G

        pressure = pressure_11 * math.exp(-(altitude - 11000) / scale_height)
        density = density_11 * math.exp(-(altitude - 11000) / scale_height)
        temperature = temperature_11

    return temperature, pressure, density

# -------------------- FORCE CALCULATIONS ----------------------

def calculate_forces(mass, wing_area, velocity, altitude, cl, cd, thrust):
    temperature, pressure, density = atmospheric_properties(altitude)

    dynamic_pressure = 0.5 * density * velocity ** 2

    lift = dynamic_pressure * wing_area * cl
    drag = dynamic_pressure * wing_area * cd
    weight = mass * G

    vertical_force = lift - weight
    horizontal_force = thrust - drag

    net_force = math.sqrt(vertical_force ** 2 + horizontal_force ** 2)
    acceleration = net_force / mass

    ld_ratio = lift / drag if drag != 0 else 0

    return {
        "temperature": temperature,
        "pressure": pressure,
        "density": density,
        "dynamic_pressure": dynamic_pressure,
        "lift": lift,
        "drag": drag,
        "weight": weight,
        "thrust": thrust,
        "vertical_force": vertical_force,
        "horizontal_force": horizontal_force,
        "net_force": net_force,
        "acceleration": acceleration,
        "ld_ratio": ld_ratio
    }

# ---------------- FLIGHT CONDITION ----------------------------

def determine_flight_condition(lift, weight, thrust, drag):
    vertical_difference = lift - weight
    horizontal_difference = thrust - drag

    tolerance_vertical = 0.05 * weight
    tolerance_horizontal = 0.05 * max(thrust, 1)

    if abs(vertical_difference) <= tolerance_vertical:
        if abs(horizontal_difference) <= tolerance_horizontal:
            return "LEVEL FLIGHT"
        elif horizontal_difference > 0:
            return "ACCELERATING"
        else:
            return "DECELERATING"
    elif vertical_difference > 0:
        return "CLIMBING"
    else:
        return "DESCENDING"

# ---------------------- GRAPH FUNCTION ------------------------

def generate_graphs(mass, wing_area, altitude, cl, cd, thrust):
    velocity_values = np.linspace(10, 150, 100)

    lift_values = []
    drag_values = []
    ld_values = []
    thrust_values = []
    weight_values = []

    _, _, density = atmospheric_properties(altitude)
    weight = mass * G

    for velocity in velocity_values:
        dynamic_pressure = 0.5 * density * velocity ** 2
        lift = dynamic_pressure * wing_area * cl
        drag = dynamic_pressure * wing_area * cd

        lift_values.append(lift)
        drag_values.append(drag)
        ld_values.append(lift / drag if drag != 0 else 0)
        thrust_values.append(thrust)
        weight_values.append(weight)

    fig, axs = plt.subplots(2, 2, figsize=(14, 10))

    # Graph 1: Lift vs Airspeed
    axs[0, 0].plot(velocity_values, lift_values, label="Lift", color='blue')
    axs[0, 0].plot(velocity_values, weight_values, label="Weight", color='red', linestyle='--')
    axs[0, 0].set_xlabel("Airspeed (m/s)")
    axs[0, 0].set_ylabel("Force (N)")
    axs[0, 0].set_title("Lift and Weight vs Airspeed")
    axs[0, 0].grid(True)
    axs[0, 0].legend()

    # Graph 2: Drag and Thrust
    axs[0, 1].plot(velocity_values, drag_values, label="Drag", color='orange')
    axs[0, 1].plot(velocity_values, thrust_values, label="Thrust", color='purple', linestyle='--')
    axs[0, 1].set_xlabel("Airspeed (m/s)")
    axs[0, 1].set_ylabel("Force (N)")
    axs[0, 1].set_title("Drag and Thrust vs Airspeed")
    axs[0, 1].grid(True)
    axs[0, 1].legend()

    # Graph 3: Lift-to-Drag Ratio
    axs[1, 0].plot(velocity_values, ld_values, label="L/D Ratio", color='green')
    axs[1, 0].set_xlabel("Airspeed (m/s)")
    axs[1, 0].set_ylabel("Lift-to-Drag Ratio")
    axs[1, 0].set_title("Lift-to-Drag Ratio vs Airspeed")
    axs[1, 0].grid(True)
    axs[1, 0].legend()

    # Graph 4: Four Forces Bar Chart at 80 m/s
    selected_velocity = 80
    dynamic_pressure = 0.5 * density * selected_velocity ** 2
    lift_80 = dynamic_pressure * wing_area * cl
    drag_80 = dynamic_pressure * wing_area * cd

    forces = [lift_80, drag_80, thrust, weight]
    names = ["Lift", "Drag", "Thrust", "Weight"]
    colors = ['blue', 'orange', 'purple', 'red']

    axs[1, 1].bar(names, forces, color=colors)
    axs[1, 1].set_xlabel("Aircraft Forces")
    axs[1, 1].set_ylabel("Force (N)")
    axs[1, 1].set_title("Four Fundamental Forces at 80 m/s")
    axs[1, 1].grid(axis="y", alpha=0.3)

    plt.tight_layout()
    plt.show()

# Define input parameters (matching default GUI values)
mass = 1200.0        # kg
wing_area = 16.0     # m²
velocity = 70.0      # m/s
altitude = 1000.0    # m
cl = 0.8             # Lift Coefficient
cd = 0.04            # Drag Coefficient
thrust = 5000.0      # N

# Run calculation
results = calculate_forces(mass, wing_area, velocity, altitude, cl, cd, thrust)
condition = determine_flight_condition(
    results["lift"], results["weight"], results["thrust"], results["drag"]
)

# Display Text-based Results
print("\n--- AIRCRAFT PERFORMANCE RESULTS ---")
for key, value in results.items():
    if isinstance(value, float):
        print(f"{key.replace('_', ' ').title():<20}: {value:.2f}")
    else:
        print(f"{key.replace('_', ' ').title():<20}: {value}")
print(f"\nFlight Condition    : {condition}")
print("------------------------------------")

# Generate Visualizations
generate_graphs(mass, wing_area, altitude, cl, cd, thrust)